const venues = [
  {
    id: "losail",
    name: "Losail International Circuit",
    address: "Lusail, P.O. Box 14555",
    city: "Lusail",
    country: "Qatar",
    flag: "🇶🇦",
    firstGP: 2004,
    active: true,
  },
  {
    id: "portimao",
    name: "Autodromo Internacional do Algarve",
    address: "Sítio do Escampadinho, 8500-338 Portimão",
    city: "Portimão",
    country: "Portugal",
    flag: "🇵🇹",
    firstGP: 2020,
    active: true,
  },
  {
    id: "cota",
    name: "Circuit of the Americas",
    address: "9201 Circuit of the Americas Blvd, Austin, TX 78617",
    city: "Austin",
    country: "United States",
    flag: "🇺🇸",
    firstGP: 2013,
    active: true,
  },
  {
    id: "jerez",
    name: "Circuito de Jerez – Ángel Nieto",
    address: "Ctra. Jerez-Arcos km. 10, 11405 Jerez de la Frontera",
    city: "Jerez de la Frontera",
    country: "Spain",
    flag: "🇪🇸",
    firstGP: 1987,
    active: true,
  },
  {
    id: "lemans",
    name: "Bugatti Circuit",
    address: "Circuit des 24 Heures, 72100 Le Mans",
    city: "Le Mans",
    country: "France",
    flag: "🇫🇷",
    firstGP: 1969,
    active: true,
  },
  {
    id: "mugello",
    name: "Autodromo Internazionale del Mugello",
    address: "Via Senni 187, 50038 Scarperia",
    city: "Scarperia",
    country: "Italy",
    flag: "🇮🇹",
    firstGP: 1976,
    active: true,
  },
  {
    id: "catalunya",
    name: "Circuit de Barcelona-Catalunya",
    address: "Carrer del Circuit, 08160 Montmeló",
    city: "Montmeló",
    country: "Spain",
    flag: "🇪🇸",
    firstGP: 1992,
    active: true,
  },
  {
    id: "assen",
    name: "TT Circuit Assen",
    address: "De Haar 9, 9405 TG Assen",
    city: "Assen",
    country: "Netherlands",
    flag: "🇳🇱",
    firstGP: 1949,
    active: true,
  },
  {
    id: "sachsenring",
    name: "Sachsenring",
    address: "An der Rennstrecke 6, 09212 Hohenstein-Ernstthal",
    city: "Hohenstein-Ernstthal",
    country: "Germany",
    flag: "🇩🇪",
    firstGP: 1961,
    active: true,
  },
  {
    id: "redbullring",
    name: "Red Bull Ring",
    address: "Rennstrecken Straße 1, 8724 Spielberg",
    city: "Spielberg",
    country: "Austria",
    flag: "🇦🇹",
    firstGP: 1971,
    active: true,
  },
  {
    id: "silverstone",
    name: "Silverstone Circuit",
    address: "Silverstone, Towcester NN12 8TN",
    city: "Silverstone",
    country: "United Kingdom",
    flag: "🇬🇧",
    firstGP: 1977,
    active: true,
  },
  {
    id: "brno",
    name: "Automotodrom Brno",
    address: "Masarykova okruh, 635 00 Brno",
    city: "Brno",
    country: "Czech Republic",
    flag: "🇨🇿",
    firstGP: 1950,
    active: false,
  },
  {
    id: "misano",
    name: "Misano World Circuit Marco Simoncelli",
    address: "Via Daijiro Kato 10, 47843 Misano Adriatico",
    city: "Misano Adriatico",
    country: "Italy",
    flag: "🇮🇹",
    firstGP: 1980,
    active: true,
  },
  {
    id: "aragon",
    name: "MotorLand Aragón",
    address: "Av. de las Olimpíadas s/n, 44600 Alcañiz",
    city: "Alcañiz",
    country: "Spain",
    flag: "🇪🇸",
    firstGP: 2010,
    active: true,
  },
  {
    id: "motegi",
    name: "Mobility Resort Motegi",
    address: "120-1 Hiyama, Motegi-machi, Haga-gun, Tochigi 321-3597",
    city: "Motegi",
    country: "Japan",
    flag: "🇯🇵",
    firstGP: 1999,
    active: true,
  },
  {
    id: "phillipisland",
    name: "Phillip Island Circuit",
    address: "Back Beach Rd, Phillip Island VIC 3922",
    city: "Phillip Island",
    country: "Australia",
    flag: "🇦🇺",
    firstGP: 1989,
    active: true,
  },
  {
    id: "sepang",
    name: "Sepang International Circuit",
    address: "64000 Sepang, Selangor",
    city: "Sepang",
    country: "Malaysia",
    flag: "🇲🇾",
    firstGP: 1999,
    active: true,
  },
  {
    id: "valencia",
    name: "Circuit Ricardo Tormo",
    address: "Autovía A-3, Km 334, 46120 Cheste",
    city: "Cheste",
    country: "Spain",
    flag: "🇪🇸",
    firstGP: 1999,
    active: true,
  },
  {
    id: "termas",
    name: "Autodromo Termas de Río Hondo",
    address: "Autopista Buenos Aires–Santiago del Estero, 4200",
    city: "Termas de Río Hondo",
    country: "Argentina",
    flag: "🇦🇷",
    firstGP: 2014,
    active: false,
  },
  {
    id: "indianapolis",
    name: "Indianapolis Motor Speedway",
    address: "4790 W 16th St, Indianapolis, IN 46222",
    city: "Indianapolis",
    country: "United States",
    flag: "🇺🇸",
    firstGP: 2008,
    active: false,
  },
  {
    id: "lagunaseca",
    name: "WeatherTech Raceway Laguna Seca",
    address: "1021 Monterey-Salinas Hwy, Salinas, CA 93908",
    city: "Salinas",
    country: "United States",
    flag: "🇺🇸",
    firstGP: 1988,
    active: false,
  },
  {
    id: "chang",
    name: "Chang International Circuit",
    address: "99 Mu 9 Phanomkhet, Buriram 31000",
    city: "Buriram",
    country: "Thailand",
    flag: "🇹🇭",
    firstGP: 2018,
    active: true,
  },
  {
    id: "mandalika",
    name: "Mandalika International Street Circuit",
    address: "KEK Mandalika, Pujut, Central Lombok Regency",
    city: "Central Lombok",
    country: "Indonesia",
    flag: "🇮🇩",
    firstGP: 2022,
    active: true,
  },
  {
    id: "buddh",
    name: "Buddh International Circuit",
    address: "Jaypee Sports City, Sector 25, Greater Noida, UP 201308",
    city: "Greater Noida",
    country: "India",
    flag: "🇮🇳",
    firstGP: 2023,
    active: false,
  },
  {
    id: "donington",
    name: "Donington Park",
    address: "Castle Donington, Derby DE74 2RP",
    city: "Castle Donington",
    country: "United Kingdom",
    flag: "🇬🇧",
    firstGP: 1987,
    active: false,
  },
  {
    id: "istanbul",
    name: "Istanbul Park",
    address: "Akfırat Mahallesi, Tuzla, 34959 Istanbul",
    city: "Istanbul",
    country: "Turkey",
    flag: "🇹🇷",
    firstGP: 2005,
    active: false,
  },
  {
    id: "shanghai",
    name: "Shanghai International Circuit",
    address: "2000 Yining Road, Jiading District, Shanghai 201815",
    city: "Shanghai",
    country: "China",
    flag: "🇨🇳",
    firstGP: 2004,
    active: false,
  },
  {
    id: "phakisa",
    name: "Phakisa Freeway",
    address: "Allanridge Road, Welkom, Free State 9459",
    city: "Welkom",
    country: "South Africa",
    flag: "🇿🇦",
    firstGP: 1999,
    active: false,
  },
];

export default venues;
