const venues = [
  {
    id: "losail",
    name: "Losail International Circuit",
    address: "Lusail, P.O. Box 14555",
    city: "Lusail",
    country: "Qatar",
    flag: "🇶🇦",
    firstGP: 2004,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Losail_International_Circuit_aerial.jpg",
    description: "Losail is a floodlit desert circuit built on the outskirts of Lusail, opened in 2004. Its wide, abrasive asphalt suits powerful MotoGP machines and traditionally hosts the season opener under lights. The fast flowing layout and high-speed corners make it a favourite for big-bike racing.",
    stats: {
      length: 5.380,
      corners: 16,
      direction: "clockwise",
      lapRecord: "1:53.380",
      lapRecordRider: "Francesco Bagnaia",
      lapRecordYear: 2023,
      capacity: 50000,
    },
    culture: "Qatar blends ultra-modern infrastructure with traditional Gulf Arab hospitality. Race weekend visitors enjoy world-class hotels, spectacular souks selling spices and gold, and the chance to sample authentic Qatari dishes like machboos (spiced rice and meat). The night race atmosphere under the floodlights gives Losail a unique, almost electric buzz unlike any other venue on the calendar.",
  },
  {
    id: "portimao",
    name: "Autodromo Internacional do Algarve",
    address: "Sítio do Escampadinho, 8500-338 Portimão",
    city: "Portimão",
    country: "Portugal",
    flag: "🇵🇹",
    firstGP: 2020,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Autódromo_Internacional_do_Algarve,_Portimão.jpg",
    description: "Autodromo Internacional do Algarve sits on undulating terrain near the fishing port of Portimão, creating dramatic elevation changes that challenge riders and thrill spectators. Opened in 2008, it joined the MotoGP calendar as an emergency venue during the COVID-19 season of 2020 and quickly earned a permanent slot. The blind crests and flowing high-speed sections reward both bravery and precise lines.",
    stats: {
      length: 4.592,
      corners: 15,
      direction: "clockwise",
      lapRecord: "1:38.989",
      lapRecordRider: "Fabio Quartararo",
      lapRecordYear: 2021,
      capacity: 125000,
    },
    culture: "The Algarve region is renowned throughout Europe for its golden cliffs, pristine beaches, and excellent seafood. Race fans typically combine the GP weekend with grilled sardines on the waterfront at Portimão, cold Super Bock beer in the sun, and day trips along the dramatic coastline to Ponta da Piedade. The Portuguese crowd is passionate and knowledgeable, making the event one of the most welcoming on the calendar.",
  },
  {
    id: "cota",
    name: "Circuit of the Americas",
    address: "9201 Circuit of the Americas Blvd, Austin, TX 78617",
    city: "Austin",
    country: "United States",
    flag: "🇺🇸",
    firstGP: 2013,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Circuit_of_the_Americas_(aerial).jpg",
    description: "Circuit of the Americas opened in 2012 in Austin, Texas, as the first purpose-built Grand Prix facility in the United States. The 5.5 km lap is anti-clockwise and features the iconic 133-foot elevated hairpin at Turn 1, inspired by Formula 1's Turkish Turn 8. Marc Márquez dominated the first decade of MotoGP racing here before Alex Rins delivered a sensational upset in 2019.",
    stats: {
      length: 5.513,
      corners: 20,
      direction: "anti-clockwise",
      lapRecord: "2:02.956",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2015,
      capacity: 120000,
    },
    culture: "Austin is the live-music capital of the world, with Sixth Street and Rainey Street packed with venues playing everything from blues to country. Race weekend coincides with the city's vibrant bar scene, legendary Texas BBQ (Franklin Barbecue draws queues before sunrise), and warm southern hospitality. The MotoGP event brings an unmistakable European and Latin American flavour to the famously eccentric Texan city.",
  },
  {
    id: "jerez",
    name: "Circuito de Jerez – Ángel Nieto",
    address: "Ctra. Jerez-Arcos km. 10, 11405 Jerez de la Frontera",
    city: "Jerez de la Frontera",
    country: "Spain",
    flag: "🇪🇸",
    firstGP: 1987,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Circuito_de_Jerez_aerial_photo.jpg",
    description: "Circuito de Jerez, renamed in honour of nine-time world champion Ángel Nieto in 2017, has hosted the Spanish Grand Prix since 1987 and is one of the most beloved rounds on the MotoGP calendar. The circuit's sweeping layout and notoriously abrasive tarmac inflict heavy tyre wear, turning strategy and mechanical sympathy into key weapons. The wildly pro-Márquez crowd creates an atmosphere that riders describe as unlike any other.",
    stats: {
      length: 4.423,
      corners: 13,
      direction: "clockwise",
      lapRecord: "1:36.223",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2019,
      capacity: 150000,
    },
    culture: "Jerez de la Frontera is the sherry capital of the world, where bodegas like González Byass and Tío Pepe have cellared fino and manzanilla for centuries. Race fans flood the grandstands wearing red and gold Spanish colours, filling the air with flags and chants. Between sessions, the cobblestoned old town invites you to tapas crawls, flamenco shows, and the world-famous Royal Andalusian School of Equestrian Art just minutes from the circuit.",
  },
  {
    id: "lemans",
    name: "Bugatti Circuit",
    address: "Circuit des 24 Heures, 72100 Le Mans",
    city: "Le Mans",
    country: "France",
    flag: "🇫🇷",
    firstGP: 1969,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Bugatti_Circuit_Le_Mans.jpg",
    description: "The Bugatti Circuit occupies the infield of the legendary Le Mans 24 Hours facility, sharing its pit straight and the famous Dunlop chicane before branching off onto its own compact layout. Despite modest dimensions, the track rewards late-braking aggression and features challenging cambered turns that can catch out even experienced riders. Rain is a near-constant threat in the French spring, making the French GP one of the most unpredictable rounds of the season.",
    stats: {
      length: 4.185,
      corners: 14,
      direction: "clockwise",
      lapRecord: "1:31.973",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2019,
      capacity: 100000,
    },
    culture: "Le Mans is steeped in motor racing history, and a MotoGP weekend allows visitors to walk the same pit lane that has seen Ferrari, Porsche, and Ayrton Senna. The Sarthe department produces outstanding wines and the city's restaurants serve exceptional rillettes (pork pâté) and tarte Tatin. French fans are among the most theatrical in motorsport, arriving in full fancy dress and creating a carnival atmosphere in the campsites that surrounds the circuit for the entire weekend.",
  },
  {
    id: "mugello",
    name: "Autodromo Internazionale del Mugello",
    address: "Via Senni 187, 50038 Scarperia",
    city: "Scarperia",
    country: "Italy",
    flag: "🇮🇹",
    firstGP: 1976,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Mugello_Circuit_aerial.jpg",
    description: "Nestled in the forested Apennine hills north of Florence, Mugello is widely considered the jewel of the MotoGP calendar. Its long, swooping layout rewards bravery through high-speed sections like Casanova-Savelli and the terrifyingly fast Arrabbiata corners. Owned by Ferrari, the circuit draws enormous Italian crowds who transform the hillside grandstands and campsites into a week-long red-and-yellow party.",
    stats: {
      length: 5.245,
      corners: 15,
      direction: "clockwise",
      lapRecord: "1:45.787",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2019,
      capacity: 90000,
    },
    culture: "Mugello sits in Tuscany, so the race experience extends well beyond the track. Visitors explore the medieval hilltop villages of Scarperia and Firenzuola, taste Chianti and Brunello di Montalcino, and feast on bistecca alla Fiorentina in Florence just 30 km away. The Mugello atmosphere is legendary in MotoGP — the camping village pulses with music and fireworks each night, and the Rossi fans in Curva del Correntaio carry on long after the last session ends.",
  },
  {
    id: "catalunya",
    name: "Circuit de Barcelona-Catalunya",
    address: "Carrer del Circuit, 08160 Montmeló",
    city: "Montmeló",
    country: "Spain",
    flag: "🇪🇸",
    firstGP: 1992,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Circuit_de_Barcelona_Catalunya_aerial.jpg",
    description: "Circuit de Barcelona-Catalunya, built on a plateau outside Montmeló, has hosted the Catalan Grand Prix continuously since 1992 and is renowned for its smooth surface and technical variety. The mix of fast sweepers, tight hairpins, and a long start-finish straight makes it an excellent all-round test of man and machine. Barcelona's accessibility means the grandstands are consistently packed with vocal Spanish and international fans.",
    stats: {
      length: 4.657,
      corners: 16,
      direction: "clockwise",
      lapRecord: "1:38.798",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2016,
      capacity: 140000,
    },
    culture: "Barcelona needs no introduction as a destination — Gaudí's Sagrada Família, the Gothic Quarter, Las Ramblas, and Barceloneta beach are all within an hour of the circuit. Race fans often split their time between the Montmeló paddock and the city, sampling tapas in the Boqueria market, watching FC Barcelona (or Espanyol) train, and soaking up the Catalan identity that makes this corner of Spain uniquely cosmopolitan and creative.",
  },
  {
    id: "assen",
    name: "TT Circuit Assen",
    address: "De Haar 9, 9405 TG Assen",
    city: "Assen",
    country: "Netherlands",
    flag: "🇳🇱",
    firstGP: 1949,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/TT_Circuit_Assen_aerial.jpg",
    description: "TT Circuit Assen, known as the Cathedral of Speed, is the only circuit to have featured on the Grand Prix calendar every single year since the World Championship began in 1949. Originally run on public roads through the town of Assen, the circuit was rebuilt in its current form in 1955 and has been continuously updated. Its fast, flowing character and beloved infield section have made it an eternal favourite among riders and fans alike.",
    stats: {
      length: 4.555,
      corners: 18,
      direction: "clockwise",
      lapRecord: "1:32.994",
      lapRecordRider: "Fabio Quartararo",
      lapRecordYear: 2021,
      capacity: 135000,
    },
    culture: "The Dutch TT is as much a national festival as a race. Assen's Saturday event draws 100,000+ fans, many cycling or motorcycling to the circuit through the flat Dutch countryside. The campsite atmosphere is legendary — Dutch fans are famously exuberant, the beer flows freely, and the evening concerts draw huge crowds. Assen town itself is charming, with a compact centre, the Drents Museum, and excellent local cheese and stroopwafels to enjoy throughout the weekend.",
  },
  {
    id: "sachsenring",
    name: "Sachsenring",
    address: "An der Rennstrecke 6, 09212 Hohenstein-Ernstthal",
    city: "Hohenstein-Ernstthal",
    country: "Germany",
    flag: "🇩🇪",
    firstGP: 1961,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Sachsenring_aerial.jpg",
    description: "The Sachsenring in Saxony is one of the most distinctive circuits on the MotoGP calendar — a compact, anti-clockwise track with severe elevation changes carved through wooded hillside terrain. Its tight layout with numerous left-handers famously favoured Marc Márquez, who won there twelve years in a row from 2010 to 2021. The circuit's roots stretch back to road-racing on public paths in the 1920s, giving it a rich history intertwined with the eastern German motorsport tradition.",
    stats: {
      length: 3.671,
      corners: 13,
      direction: "anti-clockwise",
      lapRecord: "1:20.269",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2019,
      capacity: 200000,
    },
    culture: "Hohenstein-Ernstthal sits in the Erzgebirge (Ore Mountains) region of Saxony, an area known for its mining heritage, intricate woodcarving crafts, and hearty cuisine. Fans arrive from across Germany and neighbouring countries, filling campsites along the circuit perimeter. Local bratwurst, cold Saxon beer, and the Schloss Augustusburg nearby make for a richly German race experience — the packed hillside grandstands produce an intense, close-quarters atmosphere unique to this intimate venue.",
  },
  {
    id: "redbullring",
    name: "Red Bull Ring",
    address: "Rennstrecken Straße 1, 8724 Spielberg",
    city: "Spielberg",
    country: "Austria",
    flag: "🇦🇹",
    firstGP: 1971,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Red_Bull_Ring_aerial.jpg",
    description: "The Red Bull Ring, set in the scenic Styrian mountains near Spielberg, was rebuilt and modernised by Red Bull in 2011 after lying dormant since 1987 when it was known as the Österreichring. Its short lap features dramatic elevation changes and long straights that generate some of the highest top speeds on the calendar. The compact layout means traffic is high and overtaking battles intense, regularly producing dramatic last-lap showdowns.",
    stats: {
      length: 4.318,
      corners: 12,
      direction: "clockwise",
      lapRecord: "1:23.027",
      lapRecordRider: "Andrea Dovizioso",
      lapRecordYear: 2018,
      capacity: 70000,
    },
    culture: "Styria is Austria's \"Green Heart\" — lush rolling hills, vineyards producing excellent Schilcher rosé, and charming spa towns like Bad Waltersdorf nearby. Race fans enjoy the spectacular mountain backdrop from the grandstands and the festival village behind the pit complex. Styrian pumpkin seed oil, Tafelspitz (boiled beef), and Sturm (young, fermented grape juice) are regional specialities to seek out. The nearby Lipizzaner stud farm at Piber adds a touch of imperial Austrian elegance to any race trip.",
  },
  {
    id: "silverstone",
    name: "Silverstone Circuit",
    address: "Silverstone, Towcester NN12 8TN",
    city: "Silverstone",
    country: "United Kingdom",
    flag: "🇬🇧",
    firstGP: 1977,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Silverstone_Circuit_aerial.jpg",
    description: "Silverstone, built on a Second World War RAF airfield in Northamptonshire, is the spiritual home of British motor racing and one of the fastest circuits in MotoGP. Its sweeping, high-speed layout — featuring iconic corners like Maggotts-Becketts-Chapel and Copse — demands exceptional stability at speed. The British Grand Prix at Silverstone has a proud history dating to 1977, and Cal Crutchlow's 2016 win here remains one of the most celebrated home victories in recent memory.",
    stats: {
      length: 5.900,
      corners: 18,
      direction: "clockwise",
      lapRecord: "2:01.941",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2019,
      capacity: 150000,
    },
    culture: "A Silverstone race weekend is quintessentially British — expect unpredictable weather, strong tea, fish and chips, and passionate fans in Union Jack livery. The surrounding Northamptonshire countryside offers thatched villages, excellent pubs serving real ales, and historic Blenheim Palace an hour away. The British MotoGP draws a knowledgeable crowd that cheers every rider regardless of nationality, creating an inclusive, festival atmosphere that spans an entire long weekend.",
  },
  {
    id: "brno",
    name: "Automotodrom Brno",
    address: "Masarykova okruh, 635 00 Brno",
    city: "Brno",
    country: "Czech Republic",
    flag: "🇨🇿",
    firstGP: 1950,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Automotodrom_Brno_aerial.jpg",
    description: "Automotodrom Brno, built in 1987 in a natural amphitheatre south of Brno, hosted the Czech Grand Prix until 2019 when it fell off the calendar due to rising costs and infrastructure concerns. The undulating, 5.4 km layout offered spectacular elevation changes and long, sweeping corners that were beloved by riders for their rewarding, old-school character. Its loss was widely mourned by fans who treasured the intimate, affordable atmosphere of a Czech race weekend.",
    stats: {
      length: 5.403,
      corners: 14,
      direction: "clockwise",
      lapRecord: "1:54.279",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2019,
      capacity: 200000,
    },
    culture: "Brno is the Czech Republic's second city, famous for the Tugendhat Villa (a UNESCO World Heritage masterpiece of modernist architecture), excellent Moravian wines, and one of Europe's most vibrant student populations. The Czech GP was among the best-value races on the calendar — affordable camping, outstanding local Pilsner Urquell and Budvar beer, and rich Moravian cuisine made it a pilgrimage for budget-conscious fans from across Central Europe.",
  },
  {
    id: "misano",
    name: "Misano World Circuit Marco Simoncelli",
    address: "Via Daijiro Kato 10, 47843 Misano Adriatico",
    city: "Misano Adriatico",
    country: "Italy",
    flag: "🇮🇹",
    firstGP: 1980,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Misano_World_Circuit_aerial.jpg",
    description: "Misano World Circuit Marco Simoncelli, renamed in honour of the popular Italian rider killed there in 2011, sits a kilometre from the Adriatic Sea on the Riviera Romagnola. The anti-clockwise layout features a demanding mix of slow chicanes and flowing sections, placing a premium on corner-exit drive and rear grip. The San Marino Grand Prix is Italy's second home round and draws enormous crowds of Italian fans, particularly supporters of Valentino Rossi whose home region of Tavullia is just 20 km away.",
    stats: {
      length: 4.226,
      corners: 16,
      direction: "anti-clockwise",
      lapRecord: "1:31.629",
      lapRecordRider: "Francesco Bagnaia",
      lapRecordYear: 2023,
      capacity: 80000,
    },
    culture: "Misano sits at the heart of the Riviera Romagnola, a stretch of Adriatic coast famous for its golden sandy beaches, outdoor nightclubs, and the thriving beach-bar culture of Rimini and Riccione nearby. Race weekend is a full-sensory Italian experience — the smell of sunscreen mixing with grilled piadina flatbreads, the roar of superbikes filling the campsites, and evening passeggiatas through the seafront resorts. The proximity to Valentino Rossi's hometown of Tavullia turns the event into a yellow-helmeted pilgrimage.",
  },
  {
    id: "aragon",
    name: "MotorLand Aragón",
    address: "Av. de las Olimpíadas s/n, 44600 Alcañiz",
    city: "Alcañiz",
    country: "Spain",
    flag: "🇪🇸",
    firstGP: 2010,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/MotorLand_Aragon_aerial.jpg",
    description: "MotorLand Aragón, opened in 2010 on the arid Aragonese plateau near Alcañiz, was purpose-built as a state-of-the-art motorsport complex. The 5.1 km lap features a demanding sequence of high-speed curves, two long straights generating extreme top speeds, and a signature double right-hander at the end of the back straight. The uncompromising terrain and typically dry, abrasive surface make tyre management critical.",
    stats: {
      length: 5.078,
      corners: 17,
      direction: "clockwise",
      lapRecord: "1:47.140",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2013,
      capacity: 130000,
    },
    culture: "Aragón is one of Spain's least-visited but most rewarding regions — home to the dramatic Pyrenees foothills, the medieval walled city of Alcañiz itself, and the stunning Maestrazgo highlands. Local cuisine is built around lamb chiffonnade, migas (fried breadcrumbs with chorizo), and bota wines from the Cariñena and Campo de Borja denominaciones. The Aragón GP crowd brings a passionate, grassroots energy quite different from the cosmopolitan feel of Barcelona or Jerez.",
  },
  {
    id: "motegi",
    name: "Mobility Resort Motegi",
    address: "120-1 Hiyama, Motegi-machi, Haga-gun, Tochigi 321-3597",
    city: "Motegi",
    country: "Japan",
    flag: "🇯🇵",
    firstGP: 1999,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Twin_Ring_Motegi_aerial.jpg",
    description: "Mobility Resort Motegi (formerly Twin Ring Motegi) was built by Honda in a forested area of Tochigi Prefecture, 120 km north of Tokyo, and has hosted the Japanese Grand Prix since 1999. The 4.8 km clockwise layout combines a distinctive hairpin infield section with fast, sweeping sectors and punishing braking zones. It remains a special race for Japanese manufacturers Honda, Yamaha, and Suzuki, who treat a home win as a matter of national pride.",
    stats: {
      length: 4.801,
      corners: 14,
      direction: "clockwise",
      lapRecord: "1:45.762",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2018,
      capacity: 155000,
    },
    culture: "Tochigi Prefecture is Japan's Lake District, dotted with cedar forests, traditional onsen (hot spring) resorts, and the spectacular Nikkō shrine complex — a UNESCO Heritage site. The Japanese MotoGP crowd is famously orderly, meticulous, and deeply respectful; they stand quietly at barriers and clap politely after every session, a contrast that surprises many first-time international visitors. Local bento boxes, ramen stalls, and the Honda Collection Hall (open during race week) make Motegi one of the most culturally enriching stops on the calendar.",
  },
  {
    id: "phillipisland",
    name: "Phillip Island Circuit",
    address: "Back Beach Rd, Phillip Island VIC 3922",
    city: "Phillip Island",
    country: "Australia",
    flag: "🇦🇺",
    firstGP: 1989,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Phillip_Island_Circuit_aerial.jpg",
    description: "Phillip Island Circuit is arguably the world's most spectacular motorcycle racing venue — a windswept clifftop track with panoramic views across Bass Strait and flocks of little penguins nesting in the dunes. Its fast, sweeping layout, featuring the iconic MG/Southern Loop bend and the white-knuckle Lukey Heights right-hander, generates some of the highest average speeds in MotoGP. The circuit is prone to sudden, violent wind gusts that can flip bikes and rewrite race scripts in an instant.",
    stats: {
      length: 4.448,
      corners: 12,
      direction: "clockwise",
      lapRecord: "1:27.451",
      lapRecordRider: "Cal Crutchlow",
      lapRecordYear: 2015,
      capacity: 50000,
    },
    culture: "Phillip Island is a wildlife paradise — penguins parade at dusk year-round, koalas sleep in eucalyptus trees above the circuit access road, and fur seals bask on the rocks at Cape Woolamai. Race weekend brings a laid-back Australian atmosphere with craft beer, fresh lobster from the local fishermen, and a genuine sense of remoteness rare in the global MotoGP paddock. The Melbourne skyline glitters on the horizon at night, 90 minutes away for those who want a city fix.",
  },
  {
    id: "sepang",
    name: "Sepang International Circuit",
    address: "64000 Sepang, Selangor",
    city: "Sepang",
    country: "Malaysia",
    flag: "🇲🇾",
    firstGP: 1999,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Sepang_International_Circuit_aerial.jpg",
    description: "Sepang International Circuit, designed by Hermann Tilke and opened in 1999, sits in the jungle south of Kuala Lumpur near Kuala Lumpur International Airport. Its ambitious layout — 5.5 km with sweeping high-speed sections and hard-braking hairpins — was a revelation when it debuted and has challenged riders ever since. Tropical heat and sudden, torrential downpours create notoriously unpredictable conditions that can transform the race order in seconds.",
    stats: {
      length: 5.543,
      corners: 15,
      direction: "clockwise",
      lapRecord: "1:57.587",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2015,
      capacity: 130000,
    },
    culture: "Malaysia is a melting pot of Malay, Chinese, Indian, and indigenous cultures, and the food scene is extraordinary — satay, nasi lemak, char kway teow, and roti canai are all available within the circuit precinct. Kuala Lumpur, just 45 minutes away, dazzles with the Petronas Twin Towers, vibrant street markets in Bukit Bintang, and rooftop bars with spectacular city views. Race weekend temperatures of 35°C+ and 80% humidity are part of the challenge and the charm of the Malaysian GP.",
  },
  {
    id: "valencia",
    name: "Circuit Ricardo Tormo",
    address: "Autovía A-3, Km 334, 46120 Cheste",
    city: "Cheste",
    country: "Spain",
    flag: "🇪🇸",
    firstGP: 1999,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Circuit_Ricardo_Tormo_aerial.jpg",
    description: "Circuit Ricardo Tormo, named after the Spanish motorcycle racing legend, sits in an orange-grove landscape 25 km west of Valencia and has hosted the season finale for much of MotoGP's modern era. The compact, clockwise circuit features long straights and tight hairpins that demand hard braking and aggressive acceleration, making it a circuit where bold overtaking is rewarded. As the last race of the year, Valencia has been the stage for some of the most emotionally charged championship deciders in MotoGP history.",
    stats: {
      length: 4.005,
      corners: 14,
      direction: "clockwise",
      lapRecord: "1:30.947",
      lapRecordRider: "Jorge Lorenzo",
      lapRecordYear: 2012,
      capacity: 120000,
    },
    culture: "Valencia is Spain's third city and the birthplace of paella — the proper rice dish cooked over orange-wood fires with rabbit, chicken, and local Valencian flat beans. Race weekend coincides with cooler November weather, but the grandstands still pack with passionate Spanish fans, many wearing the colours of their favourite rider. The old quarter (Barrio del Carmen), the futuristic City of Arts and Sciences designed by Santiago Calatrava, and the relaxed Mediterranean pace of life make Valencia one of the calendar's most livable race locations.",
  },
  {
    id: "termas",
    name: "Autodromo Termas de Río Hondo",
    address: "Autopista Buenos Aires–Santiago del Estero, 4200",
    city: "Termas de Río Hondo",
    country: "Argentina",
    flag: "🇦🇷",
    firstGP: 2014,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Autodromo_Termas_de_Rio_Hondo_aerial.jpg",
    description: "Autodromo Termas de Río Hondo opened in 2008 in the spa town of Termas de Río Hondo in the Santiago del Estero province of northern Argentina. The 4.8 km clockwise circuit brought MotoGP back to South America for the first time in decades when it debuted in 2014, instantly becoming one of the most atmospheric rounds on the calendar. Political and financial difficulties eventually saw it drop off the calendar after 2019.",
    stats: {
      length: 4.806,
      corners: 14,
      direction: "clockwise",
      lapRecord: "1:37.613",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2014,
      capacity: 90000,
    },
    culture: "Termas de Río Hondo is Argentina's famous thermal spa town, where visitors have soaked in the mineral-rich hot springs for over a century. Race weekend turned the remote northern city into a boisterous party for Argentina's passionate motorcycle fans — empanadas, locro stew, Malbec wine, and folkloric music filled the paddock perimeter. The raw, frontier spirit of the Argentine GP and the genuine warmth of local fans made it one of the most memorable stops on the calendar during its brief run.",
  },
  {
    id: "indianapolis",
    name: "Indianapolis Motor Speedway",
    address: "4790 W 16th St, Indianapolis, IN 46222",
    city: "Indianapolis",
    country: "United States",
    flag: "🇺🇸",
    firstGP: 2008,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Indianapolis_Motor_Speedway_aerial.jpg",
    description: "Indianapolis Motor Speedway, the legendary oval home of the Indy 500 since 1911, hosted MotoGP on its infield road course from 2008 to 2015. The purpose-built circuit used a mix of the oval banking and infield sections to create a 4.2 km layout that was challenging but lacked the character of purpose-built motorcycle circuits. Despite strong initial crowds, declining attendance and a competing calendar date led to MotoGP's departure after the 2015 edition.",
    stats: {
      length: 4.216,
      corners: 16,
      direction: "clockwise",
      lapRecord: "1:32.822",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2014,
      capacity: 250000,
    },
    culture: "Indianapolis is the racing capital of America, and the Motor Speedway itself — known as the Brickyard for its original paved brick surface — is a cathedral of motorsport history. Race fans visiting in late August could still feel the reverberations of the Indianapolis 500 earlier in the season while enjoying Midwest hospitality: pork tenderloin sandwiches, craft IPAs from Sun King Brewery, and the walkable Mass Ave arts district in downtown Indy.",
  },
  {
    id: "lagunaseca",
    name: "WeatherTech Raceway Laguna Seca",
    address: "1021 Monterey-Salinas Hwy, Salinas, CA 93908",
    city: "Salinas",
    country: "United States",
    flag: "🇺🇸",
    firstGP: 1988,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Laguna_Seca_aerial.jpg",
    description: "WeatherTech Raceway Laguna Seca, carved into the golden hills of the Monterey Peninsula, is one of the most iconic road courses in the world. Its defining feature is the Corkscrew — a combination of a sharp left followed immediately by a plummeting right, dropping almost 18 metres in the process. MotoGP raced here from 1988 through 2013, and the Corkscrew produced some of the sport's most memorable moments, most famously Casey Stoner's legendary pass on Valentino Rossi in 2008.",
    stats: {
      length: 3.610,
      corners: 11,
      direction: "clockwise",
      lapRecord: "1:21.076",
      lapRecordRider: "Casey Stoner",
      lapRecordYear: 2008,
      capacity: 75000,
    },
    culture: "Laguna Seca sits in the heart of Monterey County, just minutes from the Pacific Coast, Carmel-by-the-Sea, and the world-renowned Pebble Beach estate. Race weekend in July coincides with the peak of summer, and the California lifestyle — avocado toast, craft wine from the Carmel Valley, and spectacular ocean views — makes it one of the most lifestyle-rich race venues in the sport's history. The Corkscrew alone justifies the trip.",
  },
  {
    id: "chang",
    name: "Chang International Circuit",
    address: "99 Mu 9 Phanomkhet, Buriram 31000",
    city: "Buriram",
    country: "Thailand",
    flag: "🇹🇭",
    firstGP: 2018,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Chang_International_Circuit_aerial.jpg",
    description: "Chang International Circuit in Buriram, northeast Thailand, is one of the most modern facilities in MotoGP — a gleaming, state-of-the-art complex opened in 2014 and integrated with a football stadium, hotel, and entertainment complex. The 4.5 km clockwise layout features long straights and heavy-braking corners that generate enormous overtaking opportunities. Thailand joined the MotoGP calendar in 2018, instantly drawing enormous crowds of passionate Thai motorcycle fans.",
    stats: {
      length: 4.554,
      corners: 12,
      direction: "clockwise",
      lapRecord: "1:29.799",
      lapRecordRider: "Marc Márquez",
      lapRecordYear: 2019,
      capacity: 100000,
    },
    culture: "Buriram province is the heart of Isan culture — northeastern Thailand's distinct regional identity with its own cuisine (spicy larb salads, sticky rice, grilled catfish), music, and traditions influenced by the ancient Khmer Empire. The nearby Phanom Rung Historical Park, a spectacular 10th-century Khmer temple complex, is one of Southeast Asia's great archaeological treasures. The Thai GP crowd is among the most colourful on the calendar — fans arrive in full national dress, carrying enormous Thai flags and creating a cacophony of homemade drums and horns.",
  },
  {
    id: "mandalika",
    name: "Mandalika International Street Circuit",
    address: "KEK Mandalika, Pujut, Central Lombok Regency",
    city: "Central Lombok",
    country: "Indonesia",
    flag: "🇮🇩",
    firstGP: 2022,
    active: true,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Mandalika_International_Street_Circuit_aerial.jpg",
    description: "Mandalika International Street Circuit was built on the spectacular southern coast of Lombok island, carving through a coastal resort development with ocean views from parts of the circuit. Opened in 2021 and hosting MotoGP from 2022, it is one of the newest venues on the calendar. The 4 km layout's combination of tight sections, heavy braking zones, and strong ocean winds creates a physically demanding race, often in intense tropical heat.",
    stats: {
      length: 4.031,
      corners: 17,
      direction: "clockwise",
      lapRecord: "1:31.067",
      lapRecordRider: "Jorge Martín",
      lapRecordYear: 2022,
      capacity: 150000,
    },
    culture: "Lombok and the nearby Gili Islands are Indonesia's most stunning beach destinations — pristine white-sand beaches, crystal-clear turquoise water, and some of the best diving and snorkelling in Asia draw visitors from around the world. Race weekend combines high-intensity motorsport with the laid-back Hindu and Sasak Muslim culture of Lombok, where traditional weaving and pottery villages sit minutes from the circuit. Fresh seafood barbecues on the beach and towering Mount Rinjani as a backdrop make Mandalika uniquely spectacular.",
  },
  {
    id: "buddh",
    name: "Buddh International Circuit",
    address: "Jaypee Sports City, Sector 25, Greater Noida, UP 201308",
    city: "Greater Noida",
    country: "India",
    flag: "🇮🇳",
    firstGP: 2023,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Buddh_International_Circuit_aerial.jpg",
    description: "Buddh International Circuit in Greater Noida, designed by Hermann Tilke, hosted the Indian Grand Prix for one MotoGP season in 2023 before being dropped from the calendar. The 5.1 km clockwise layout features a blend of fast sweeping sections and heavy-braking hairpins, with some of the longest straights in MotoGP generating extreme top speeds. India's enormous market of over 200 million motorcycle riders made the event commercially enticing despite infrastructural and regulatory challenges.",
    stats: {
      length: 5.125,
      corners: 16,
      direction: "clockwise",
      lapRecord: "1:46.913",
      lapRecordRider: "Francesco Bagnaia",
      lapRecordYear: 2023,
      capacity: 120000,
    },
    culture: "Greater Noida sits at the edge of the NCR (National Capital Region) and gives access to Delhi's extraordinary cultural riches — the Red Fort, Qutb Minar, Humayun's Tomb, and the sensory overload of Chandni Chowk's street food bazaar. India's motorcycle culture is unlike anywhere else on earth: over 20 million bikes are sold every year, and the race drew enormous interest from enthusiasts who had never seen a MotoGP event live. Street food stalls around the circuit offered chaat, butter chicken, and fresh mango lassi.",
  },
  {
    id: "donington",
    name: "Donington Park",
    address: "Castle Donington, Derby DE74 2RP",
    city: "Castle Donington",
    country: "United Kingdom",
    flag: "🇬🇧",
    firstGP: 1987,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Donington_Park_aerial.jpg",
    description: "Donington Park, set in the rolling Leicestershire countryside near East Midlands Airport, was the home of British motorcycle Grand Prix racing before Silverstone took over in 2010. The circuit's swooping Craner Curves section and old-school character made it a fan favourite among riders who lamented its loss. Financial difficulties with the venue's owners interrupted a planned redevelopment project, and the British GP moved permanently to Silverstone during the construction standstill.",
    stats: {
      length: 4.023,
      corners: 12,
      direction: "clockwise",
      lapRecord: "1:27.745",
      lapRecordRider: "Casey Stoner",
      lapRecordYear: 2009,
      capacity: 150000,
    },
    culture: "Donington Park sits in the East Midlands, close to the village of Castle Donington and the market town of Derby. Race weekend brought the best of British festival culture: elaborate fancy-dress enclosures, muddy campsites in the English tradition, and the unmistakable smell of burgers and rain. Nearby Nottingham — home of Robin Hood legend, Nottingham Castle, and the Nottingham lace industry — offered welcome culture for those not entirely absorbed in the paddock.",
  },
  {
    id: "istanbul",
    name: "Istanbul Park",
    address: "Akfırat Mahallesi, Tuzla, 34959 Istanbul",
    city: "Istanbul",
    country: "Turkey",
    flag: "🇹🇷",
    firstGP: 2005,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Istanbul_Park_aerial.jpg",
    description: "Istanbul Park, a Hermann Tilke-designed circuit on the Asian side of the Bosphorus near Tuzla, hosted MotoGP from 2005 to 2007 and was famous for its spectacular Turn 8 — a long, banked, multi-apex left-hander that has since become iconic in Formula 1. The anti-clockwise layout with sweeping high-speed corners suited powerful MotoGP machines perfectly. Financial difficulties and contractual disputes ended its brief MotoGP tenure after only three editions.",
    stats: {
      length: 5.338,
      corners: 14,
      direction: "anti-clockwise",
      lapRecord: "1:58.858",
      lapRecordRider: "Valentino Rossi",
      lapRecordYear: 2005,
      capacity: 155000,
    },
    culture: "Istanbul straddles two continents and two worlds, and visiting for a race meant mingling the paddock world with the extraordinary culture of one of history's great cities. The Hagia Sophia, Blue Mosque, Grand Bazaar, and the spice-scented streets of Beyoğlu were all within reach. Turkish hospitality is legendary — çay (tea) and fresh simit bread are offered at every opportunity, and the evening meze tables piled with börek, hummus, and grilled meats made Istanbul one of the most pleasurable race destinations in the sport's history.",
  },
  {
    id: "shanghai",
    name: "Shanghai International Circuit",
    address: "2000 Yining Road, Jiading District, Shanghai 201815",
    city: "Shanghai",
    country: "China",
    flag: "🇨🇳",
    firstGP: 2004,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Shanghai_International_Circuit_aerial.jpg",
    description: "Shanghai International Circuit, another Hermann Tilke design opened in 2004, brought MotoGP to mainland China for the first time when it debuted as part of the inaugural season calendar. The 5.4 km anti-clockwise layout — distinguished by its unique \"snail-shaped\" pit complex and Turn 1-2 sweeper — was technically demanding but struggled to generate the close racing and passionate crowds that characterised the best Grand Prix venues. The circuit dropped from the MotoGP calendar after the 2008 season.",
    stats: {
      length: 5.451,
      corners: 16,
      direction: "clockwise",
      lapRecord: "2:02.960",
      lapRecordRider: "Sete Gibernau",
      lapRecordYear: 2004,
      capacity: 200000,
    },
    culture: "Shanghai is a dazzling, ultra-modern megalopolis where Art Deco Bund architecture faces a skyline of record-breaking towers across the Huangpu River. Race weekends in the Jiading district gave fans access to local street food markets serving xiaolongbao (soup dumplings), scallion pancakes, and char siu bao alongside the circuit's international offerings. The city's energy, shopping in Nanjing Road, and the historic Yu Garden quarter made Shanghai one of the most exciting — if challenging — locations the sport has visited.",
  },
  {
    id: "phakisa",
    name: "Phakisa Freeway",
    address: "Allanridge Road, Welkom, Free State 9459",
    city: "Welkom",
    country: "South Africa",
    flag: "🇿🇦",
    firstGP: 1999,
    active: false,
    img: "https://commons.wikimedia.org/wiki/Special:FilePath/Phakisa_Freeway_aerial.jpg",
    description: "Phakisa Freeway in Welkom, Free State, was the only MotoGP circuit in Africa during the modern era, built on the site of a former gold mining town. The circuit's name means \"hurry up\" in Sesotho, a reference to South Africa's post-apartheid development ambitions, and it hosted MotoGP from 1999 to 2004. The layout's long, sweeping main straight and challenging hairpin section produced exciting racing but the remote location and difficult economics made sustaining the event impossible.",
    stats: {
      length: 4.243,
      corners: 13,
      direction: "clockwise",
      lapRecord: "1:33.861",
      lapRecordRider: "Valentino Rossi",
      lapRecordYear: 2004,
      capacity: 60000,
    },
    culture: "Welkom sits in the South African highveld, a flat, gold-rush landscape quite unlike the safari and coastal imagery most associate with South Africa. Race weekends brought an unusual mix of Afrikaner farm culture, South African braai (barbecue) traditions, and the passionate local motorcycle racing scene. Nearby Bloemfontein offers the Oliewenhuis Art Museum and the Anglo-Boer War Museum, while the highveld's vast skies and dramatic thunderstorms provided a memorable backdrop quite unlike any other Grand Prix destination.",
  },
];

export default venues;
